#!/bin/bash

## To use this hook execute in the project root:
## git config --local core.hooksPath .githooks/
if npm run lint; then
    npx hardhat compile --force
    npm run docgen
    git add docs
    cp artifacts/contracts/Supernets2dot0Bridge.sol/Supernets2dot0Bridge.json compiled-contracts/
    cp artifacts/contracts/Supernets2dot0GlobalExitRoot.sol/Supernets2dot0GlobalExitRoot.json compiled-contracts/
    cp artifacts/contracts/Supernets2dot0GlobalExitRootL2.sol/Supernets2dot0GlobalExitRootL2.json compiled-contracts/
    cp artifacts/contracts/lib/TokenWrapped.sol/TokenWrapped.json compiled-contracts/
    cp artifacts/contracts/mocks/Supernets2dot0BridgeMock.sol/Supernets2dot0BridgeMock.json compiled-contracts/
    cp artifacts/contracts/mocks/ERC20PermitMock.sol/ERC20PermitMock.json compiled-contracts/
    cp artifacts/contracts/mocks/Supernets2dot0GlobalExitRootL2Mock.sol/Supernets2dot0GlobalExitRootL2Mock.json compiled-contracts/
    cp artifacts/contracts/mocks/Supernets2dot0GlobalExitRootMock.sol/Supernets2dot0GlobalExitRootMock.json compiled-contracts/
    cp artifacts/contracts/mocks/Supernets2dot0Mock.sol/Supernets2dot0Mock.json compiled-contracts/
    cp artifacts/contracts/mocks/VerifierRollupHelperMock.sol/VerifierRollupHelperMock.json compiled-contracts/
    cp artifacts/contracts/Supernets2dot0.sol/Supernets2dot0.json compiled-contracts/
    cp artifacts/contracts/verifiers/FflonkVerifier.sol/FflonkVerifier.json compiled-contracts/
    cp artifacts/@openzeppelin/contracts/proxy/transparent/ProxyAdmin.sol/ProxyAdmin.json compiled-contracts/
    cp artifacts/@openzeppelin/contracts/proxy/transparent/TransparentUpgradeableProxy.sol/TransparentUpgradeableProxy.json compiled-contracts/
    cp artifacts/contracts/deployment/Supernets2dot0Deployer.sol/Supernets2dot0Deployer.json compiled-contracts/
    cp artifacts/contracts/Supernets2dot0Timelock.sol/Supernets2dot0Timelock.json compiled-contracts/
    git add compiled-contracts
    exit 0
else
    exit 1
fi

